//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/GloablGameJam/PlayerInputActions/GGJ_PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/GloablGameJam/PlayerInputActions/GGJ_PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GGJ_PlayerInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GGJ_PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GGJ_PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""GlobalGameJam"",
            ""id"": ""dd509bee-4acf-4acf-a5b1-cf872d0bcdfa"",
            ""actions"": [
                {
                    ""name"": ""CharacterMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8ad10b0-6bf0-42ff-9e55-d1945d6e479a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterRotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8cb14b09-8561-46a9-8dbe-0e85dbe9de2f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterSprint"",
                    ""type"": ""Button"",
                    ""id"": ""15cd0e47-8ca1-413e-90bf-07d8208faa00"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterCrouch"",
                    ""type"": ""Button"",
                    ""id"": ""30a2777a-62e5-456a-ad6f-395606b1e6a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterJump"",
                    ""type"": ""Button"",
                    ""id"": ""a017d4a2-2c71-4cc2-9412-915f570ac4da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropMask"",
                    ""type"": ""Button"",
                    ""id"": ""4fe49d55-0fcf-48fb-b1b5-853a630dfadb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""67dbb7f8-9e3e-430a-b0e5-e5292e2ab8f3"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0407ab78-96b5-49ff-9f34-fd1fd49196cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""418ee08a-f58c-469b-a603-064bd7602345"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f23cbb6e-22d2-4d4c-a1be-18aa50026878"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a24f00bd-83d8-4f5c-91b0-ff080763920d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""7f95ee6d-998c-4d27-8311-420ac60a2aaa"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6bc9e4b6-1ecd-4f3a-a4ff-296db906c937"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8e190dc1-0529-4e41-b508-fb67e4400397"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a6c0b4ac-4fac-499a-a41b-2c5b635ff12d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fd088037-8e8f-4774-a2a9-db302cb249da"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6306d211-0029-468c-a622-f8861dcbbeaf"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""1ad0ee1f-fc02-4344-b30f-b3ed2edde7f3"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ed59007-5162-4f07-b989-3c9643634bef"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c60530d6-ca3c-42e9-812e-928b63c79571"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""79ac5949-a448-42a6-8954-95d23ba63733"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6293ec3b-716f-4c07-af1c-484b2e3f47bc"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f3714da8-9397-4dfd-a2e2-c1fa82e155b1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19a4f562-9ced-4ebb-a8c3-3b32bea887fb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f94ab7a8-cc10-481b-bb63-567393c7d661"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterCrouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8d234ea-c371-4daa-b39c-26c2d1a69317"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c6e5903-cf2c-45cd-a3de-6eca2d925e3d"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropMask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GlobalGameJam
        m_GlobalGameJam = asset.FindActionMap("GlobalGameJam", throwIfNotFound: true);
        m_GlobalGameJam_CharacterMovement = m_GlobalGameJam.FindAction("CharacterMovement", throwIfNotFound: true);
        m_GlobalGameJam_CharacterRotation = m_GlobalGameJam.FindAction("CharacterRotation", throwIfNotFound: true);
        m_GlobalGameJam_CharacterSprint = m_GlobalGameJam.FindAction("CharacterSprint", throwIfNotFound: true);
        m_GlobalGameJam_CharacterCrouch = m_GlobalGameJam.FindAction("CharacterCrouch", throwIfNotFound: true);
        m_GlobalGameJam_CharacterJump = m_GlobalGameJam.FindAction("CharacterJump", throwIfNotFound: true);
        m_GlobalGameJam_DropMask = m_GlobalGameJam.FindAction("DropMask", throwIfNotFound: true);
    }

    ~@GGJ_PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_GlobalGameJam.enabled, "This will cause a leak and performance issues, GGJ_PlayerInputActions.GlobalGameJam.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GlobalGameJam
    private readonly InputActionMap m_GlobalGameJam;
    private List<IGlobalGameJamActions> m_GlobalGameJamActionsCallbackInterfaces = new List<IGlobalGameJamActions>();
    private readonly InputAction m_GlobalGameJam_CharacterMovement;
    private readonly InputAction m_GlobalGameJam_CharacterRotation;
    private readonly InputAction m_GlobalGameJam_CharacterSprint;
    private readonly InputAction m_GlobalGameJam_CharacterCrouch;
    private readonly InputAction m_GlobalGameJam_CharacterJump;
    private readonly InputAction m_GlobalGameJam_DropMask;
    /// <summary>
    /// Provides access to input actions defined in input action map "GlobalGameJam".
    /// </summary>
    public struct GlobalGameJamActions
    {
        private @GGJ_PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GlobalGameJamActions(@GGJ_PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/CharacterMovement".
        /// </summary>
        public InputAction @CharacterMovement => m_Wrapper.m_GlobalGameJam_CharacterMovement;
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/CharacterRotation".
        /// </summary>
        public InputAction @CharacterRotation => m_Wrapper.m_GlobalGameJam_CharacterRotation;
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/CharacterSprint".
        /// </summary>
        public InputAction @CharacterSprint => m_Wrapper.m_GlobalGameJam_CharacterSprint;
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/CharacterCrouch".
        /// </summary>
        public InputAction @CharacterCrouch => m_Wrapper.m_GlobalGameJam_CharacterCrouch;
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/CharacterJump".
        /// </summary>
        public InputAction @CharacterJump => m_Wrapper.m_GlobalGameJam_CharacterJump;
        /// <summary>
        /// Provides access to the underlying input action "GlobalGameJam/DropMask".
        /// </summary>
        public InputAction @DropMask => m_Wrapper.m_GlobalGameJam_DropMask;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GlobalGameJam; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GlobalGameJamActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GlobalGameJamActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GlobalGameJamActions" />
        public void AddCallbacks(IGlobalGameJamActions instance)
        {
            if (instance == null || m_Wrapper.m_GlobalGameJamActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GlobalGameJamActionsCallbackInterfaces.Add(instance);
            @CharacterMovement.started += instance.OnCharacterMovement;
            @CharacterMovement.performed += instance.OnCharacterMovement;
            @CharacterMovement.canceled += instance.OnCharacterMovement;
            @CharacterRotation.started += instance.OnCharacterRotation;
            @CharacterRotation.performed += instance.OnCharacterRotation;
            @CharacterRotation.canceled += instance.OnCharacterRotation;
            @CharacterSprint.started += instance.OnCharacterSprint;
            @CharacterSprint.performed += instance.OnCharacterSprint;
            @CharacterSprint.canceled += instance.OnCharacterSprint;
            @CharacterCrouch.started += instance.OnCharacterCrouch;
            @CharacterCrouch.performed += instance.OnCharacterCrouch;
            @CharacterCrouch.canceled += instance.OnCharacterCrouch;
            @CharacterJump.started += instance.OnCharacterJump;
            @CharacterJump.performed += instance.OnCharacterJump;
            @CharacterJump.canceled += instance.OnCharacterJump;
            @DropMask.started += instance.OnDropMask;
            @DropMask.performed += instance.OnDropMask;
            @DropMask.canceled += instance.OnDropMask;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GlobalGameJamActions" />
        private void UnregisterCallbacks(IGlobalGameJamActions instance)
        {
            @CharacterMovement.started -= instance.OnCharacterMovement;
            @CharacterMovement.performed -= instance.OnCharacterMovement;
            @CharacterMovement.canceled -= instance.OnCharacterMovement;
            @CharacterRotation.started -= instance.OnCharacterRotation;
            @CharacterRotation.performed -= instance.OnCharacterRotation;
            @CharacterRotation.canceled -= instance.OnCharacterRotation;
            @CharacterSprint.started -= instance.OnCharacterSprint;
            @CharacterSprint.performed -= instance.OnCharacterSprint;
            @CharacterSprint.canceled -= instance.OnCharacterSprint;
            @CharacterCrouch.started -= instance.OnCharacterCrouch;
            @CharacterCrouch.performed -= instance.OnCharacterCrouch;
            @CharacterCrouch.canceled -= instance.OnCharacterCrouch;
            @CharacterJump.started -= instance.OnCharacterJump;
            @CharacterJump.performed -= instance.OnCharacterJump;
            @CharacterJump.canceled -= instance.OnCharacterJump;
            @DropMask.started -= instance.OnDropMask;
            @DropMask.performed -= instance.OnDropMask;
            @DropMask.canceled -= instance.OnDropMask;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GlobalGameJamActions.UnregisterCallbacks(IGlobalGameJamActions)" />.
        /// </summary>
        /// <seealso cref="GlobalGameJamActions.UnregisterCallbacks(IGlobalGameJamActions)" />
        public void RemoveCallbacks(IGlobalGameJamActions instance)
        {
            if (m_Wrapper.m_GlobalGameJamActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GlobalGameJamActions.AddCallbacks(IGlobalGameJamActions)" />
        /// <seealso cref="GlobalGameJamActions.RemoveCallbacks(IGlobalGameJamActions)" />
        /// <seealso cref="GlobalGameJamActions.UnregisterCallbacks(IGlobalGameJamActions)" />
        public void SetCallbacks(IGlobalGameJamActions instance)
        {
            foreach (var item in m_Wrapper.m_GlobalGameJamActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GlobalGameJamActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GlobalGameJamActions" /> instance referencing this action map.
    /// </summary>
    public GlobalGameJamActions @GlobalGameJam => new GlobalGameJamActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GlobalGameJam" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GlobalGameJamActions.AddCallbacks(IGlobalGameJamActions)" />
    /// <seealso cref="GlobalGameJamActions.RemoveCallbacks(IGlobalGameJamActions)" />
    public interface IGlobalGameJamActions
    {
        /// <summary>
        /// Method invoked when associated input action "CharacterMovement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCharacterMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CharacterRotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCharacterRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CharacterSprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCharacterSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CharacterCrouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCharacterCrouch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CharacterJump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCharacterJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DropMask" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDropMask(InputAction.CallbackContext context);
    }
}
